"use client";
import { CheckCircle2, Play, Upload } from "lucide-react";
import { useState } from "react";
import { adActions } from "@/lib/operations-data";

const badge: Record<string,string> = {"新增投放":"bg-blue-50 text-blue-700","否定关键词":"bg-red-50 text-red-700","加预算提价":"bg-emerald-50 text-emerald-700","降价":"bg-amber-50 text-amber-700","维持":"bg-slate-100 text-slate-600"};
export function AdsOptimizer() {
 const [goal,setGoal]=useState("平衡增长"); const [ran,setRan]=useState(false);
 return <><section className="rounded-2xl border border-[#dce5e0] bg-white p-5 shadow-panel"><div className="grid gap-4 lg:grid-cols-[1fr_1fr_1fr_auto]"><label className="text-sm font-medium">目标 ASIN<input defaultValue="B0D7MC810A" className="mt-2 h-11 w-full rounded-xl border border-[#d7e0db] px-3 font-mono outline-none focus:border-forest"/></label><label className="text-sm font-medium">分析周期<select className="mt-2 h-11 w-full rounded-xl border border-[#d7e0db] bg-white px-3"><option>最近 30 天</option><option>最近 60 天</option></select></label><label className="text-sm font-medium">优化目标<select value={goal} onChange={e=>setGoal(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#d7e0db] bg-white px-3"><option>平衡增长</option><option>降低 ACOS</option><option>扩大曝光</option></select></label><button onClick={()=>setRan(true)} className="mt-auto flex h-11 items-center justify-center gap-2 rounded-xl bg-forest px-5 text-sm font-semibold text-white"><Play size={16}/>运行诊断</button></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-[#f3f7f5] px-4 py-3 text-sm text-[#607068]"><Upload size={16}/>当前使用模拟广告报表；支持未来导入 Amazon Ads CSV 或连接领星。</div></section>
 <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["广告花费","$456"],["广告销售额","$1,474"],["ACOS","30.9%"],["可节省预算","$171/月"],["待执行动作","4 项"]].map((x,i)=><div key={x[0]} className="rounded-2xl border border-[#dce5e0] bg-white p-5"><p className="text-sm text-[#748078]">{x[0]}</p><p className={`mt-2 text-2xl font-bold ${i===3?"text-forest":""}`}>{x[1]}</p></div>)}</div>
 <section className="mt-5 overflow-hidden rounded-2xl border border-[#dce5e0] bg-white shadow-panel"><div className="flex items-center justify-between p-5"><div><h2 className="font-bold">广告操作清单</h2><p className="mt-1 text-sm text-[#748078]">基于盈亏 ACOS、排名变化、转化与真实搜索词信号分类。</p></div>{ran&&<span className="flex items-center gap-1 text-sm font-semibold text-forest"><CheckCircle2 size={16}/>诊断已更新</span>}</div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#fafcfb] text-xs text-[#78847d]"><tr><th className="px-5 py-4">操作</th><th>关键词</th><th>匹配</th><th>花费</th><th>销售额</th><th>ACOS</th><th>当前竞价</th><th>建议竞价</th><th>判断依据</th></tr></thead><tbody>{adActions.map(a=><tr key={a.keyword} className="border-t border-[#edf1ef]"><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${badge[a.type]}`}>{a.type}</span></td><td className="font-semibold">{a.keyword}</td><td>{a.match}</td><td>${a.spend}</td><td>${a.sales}</td><td>{a.acos?`${a.acos}%`:"—"}</td><td>{a.currentBid?`$${a.currentBid}`:"—"}</td><td className="font-bold text-forest">{a.suggestedBid?`$${a.suggestedBid}`:"—"}</td><td className="max-w-[260px] py-4 pr-5 text-[#66736b]">{a.reason}</td></tr>)}</tbody></table></div></section></>;
}
