"use client";
import { Download, Filter, Search, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import { keywordRows } from "@/lib/operations-data";

export function KeywordWorkbench() {
  const [query, setQuery] = useState(""); const [priority, setPriority] = useState("全部层级"); const [minVolume, setMinVolume] = useState(0);
  const rows = useMemo(() => keywordRows.filter(k => k.keyword.includes(query.toLowerCase()) && (priority === "全部层级" || k.priority.startsWith(priority)) && k.volume >= minVolume), [query, priority, minVolume]);
  return <>
    <div className="grid gap-3 sm:grid-cols-3">{[["关键词总量","286","去重后有效词"],["总搜索量","95.5K","月度搜索需求"],["P1 核心词","42","优先进入标题/广告"]].map(x=><div key={x[0]} className="rounded-2xl border border-[#dce5e0] bg-white p-5 shadow-panel"><p className="text-sm text-[#6f7b74]">{x[0]}</p><p className="mt-2 text-3xl font-bold">{x[1]}</p><p className="mt-2 text-xs text-[#879189]">{x[2]}</p></div>)}</div>
    <section className="mt-5 overflow-hidden rounded-2xl border border-[#dce5e0] bg-white shadow-panel"><div className="flex flex-col gap-3 border-b border-[#e5ebe7] p-5 xl:flex-row xl:items-center"><label className="flex h-11 flex-1 items-center gap-2 rounded-xl border border-[#d7e0db] px-3"><Search size={17} className="text-[#859088]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索关键词…" className="w-full outline-none"/></label><select value={priority} onChange={e=>setPriority(e.target.value)} className="h-11 rounded-xl border border-[#d7e0db] bg-white px-3 text-sm"><option>全部层级</option><option>P1</option><option>P2</option><option>P3</option></select><select value={minVolume} onChange={e=>setMinVolume(Number(e.target.value))} className="h-11 rounded-xl border border-[#d7e0db] bg-white px-3 text-sm"><option value="0">不限搜索量</option><option value="10000">搜索量 ≥ 10K</option><option value="20000">搜索量 ≥ 20K</option></select><button className="flex h-11 items-center justify-center gap-2 rounded-xl bg-forest px-4 text-sm font-semibold text-white"><Download size={16}/>导出词库</button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#fafcfb] text-xs uppercase tracking-wide text-[#7d8982]"><tr><th className="px-5 py-4">关键词</th><th>搜索量</th><th>购买率</th><th>SPR</th><th>CPC</th><th>自然排名</th><th>趋势</th><th>机会分</th><th>分层</th></tr></thead><tbody>{rows.map(k=><tr key={k.keyword} className="border-t border-[#edf1ef]"><td className="px-5 py-4"><b>{k.keyword}</b><span className="ml-2 rounded bg-[#eef3f0] px-2 py-1 text-xs text-[#66736b]">{k.intent}</span></td><td>{k.volume.toLocaleString()}</td><td>{k.purchaseRate}%</td><td>{k.spr}</td><td>${k.cpc}</td><td>#{k.naturalRank}</td><td className={k.trend>0?"text-forest":"text-red-600"}>{k.trend>0?"+":""}{k.trend}%</td><td><span className="font-bold text-forest">{k.score}</span></td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${k.priority.startsWith("P1")?"bg-forest text-white":k.priority.startsWith("P2")?"bg-[#e7f6ed] text-forest":"bg-[#f1f3f2] text-[#68736d]"}`}>{k.priority}</span></td></tr>)}</tbody></table></div><div className="border-t border-[#e5ebe7] px-5 py-3 text-sm text-[#748078]">显示 {rows.length} 个示例词 · 数据为模拟层，后续可接卖家精灵或导入 CSV</div>
    </section>
  </>;
}
