"use client";
import { Check, Copy, Sparkles } from "lucide-react";
import { useState } from "react";

const initialBullets=["STRONG MAGNETIC HOLD — Keeps charging cables, USB cords, and small desk wires securely in place while staying easy to remove with one hand.","CLEANER DESK IN SECONDS — Route daily-use cables along your desktop or nightstand and stop cords from slipping behind furniture.","FLEXIBLE CABLE FIT — Soft silicone channels hold common charging and accessory cables without pinching or damaging the outer jacket.","PEEL, PLACE & ORGANIZE — Apply the adhesive base to a clean, dry surface, then position the magnetic clips wherever your setup needs them.","FOR WORK & HOME — A compact cable-management solution for desks, bedside tables, gaming stations, and shared charging areas."];
export function ListingStudio(){const [generated,setGenerated]=useState(false);const [title,setTitle]=useState("Magnetic Cable Organizer for Desk, 6-Pack Cord Holder for Charging Cables");const [bullets,setBullets]=useState(initialBullets); const generate=()=>{setGenerated(true);setTitle("Magnetic Cable Organizer for Desk, 6-Pack Cord Holder for Charging Cables");setBullets(initialBullets)};
return <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><section className="h-fit rounded-2xl border border-[#dce5e0] bg-white p-5 shadow-panel"><h2 className="font-bold">产品事实与写作约束</h2><p className="mt-1 text-sm text-[#748078]">只使用已确认事实，避免把竞品宣称写成自己的卖点。</p><div className="mt-5 space-y-4">{[["品牌","[BRAND]"],["产品类型","Magnetic cable organizer"],["材质","Soft silicone + magnet"],["套装数量","6-pack"],["核心场景","Desk, nightstand, gaming setup"]].map(x=><label key={x[0]} className="block text-sm font-medium">{x[0]}<input defaultValue={x[1]} className="mt-2 h-10 w-full rounded-lg border border-[#d7e0db] px-3 outline-none focus:border-forest"/></label>)}<label className="block text-sm font-medium">定位方向<select className="mt-2 h-10 w-full rounded-lg border border-[#d7e0db] bg-white px-3"><option>场景体验优先</option><option>功能参数优先</option><option>性价比优先</option></select></label></div><button onClick={generate} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-forest font-semibold text-white"><Sparkles size={17}/>生成合规 Listing</button><p className="mt-3 text-xs leading-5 text-[#849087]">标题目标 ≤75 字符 · 五点每条 ≤200 字符 · Search Terms ≤249 bytes</p></section>
<section className="rounded-2xl border border-[#dce5e0] bg-white shadow-panel"><div className="flex items-center justify-between border-b border-[#e5ebe7] p-5"><div><h2 className="font-bold">美国站 Listing 草稿</h2><p className="mt-1 text-sm text-[#748078]">关键词分层：标题 L1 · 五点 L3 · 后台词 L4</p></div>{generated&&<span className="flex items-center gap-1 text-sm font-semibold text-forest"><Check size={16}/>已重新生成</span>}</div><div className="space-y-6 p-5"><Field label="标题" count={`${title.length}/75`} value={title} onChange={setTitle}/><div><div className="mb-2 flex justify-between"><label className="text-sm font-bold">五点描述</label><span className="text-xs text-[#7a867f]">5 条</span></div><div className="space-y-3">{bullets.map((b,i)=><div key={i} className="relative"><textarea value={b} onChange={e=>setBullets(v=>v.map((x,j)=>j===i?e.target.value:x))} className="min-h-24 w-full rounded-xl border border-[#d7e0db] p-3 pr-12 text-sm leading-6 outline-none focus:border-forest"/><span className="absolute bottom-3 right-3 text-xs text-[#879189]">{b.length}/200</span></div>)}</div></div><Field label="Backend Search Terms" count="137/249 bytes" value="wire management clips cord keeper desktop cable tidy charger holder nightstand gaming setup usb lead organizer"/><div className="rounded-xl border border-[#cfe3d8] bg-[#f0f8f4] p-4 text-sm leading-6 text-[#476657]"><b className="text-forest">关键词覆盖建议：</b> 标题覆盖 magnetic cable organizer、cord holder；五点补充 desk cable management clips 和场景词；后台词保留前台未覆盖同义词，避免重复和竞品品牌。</div></div></section></div>}
function Field({label,count,value,onChange}:{label:string;count:string;value:string;onChange?:(v:string)=>void}){return <div><div className="mb-2 flex justify-between"><label className="text-sm font-bold">{label}</label><span className="text-xs text-[#7a867f]">{count}</span></div><div className="relative"><textarea value={value} onChange={e=>onChange?.(e.target.value)} readOnly={!onChange} className="min-h-20 w-full rounded-xl border border-[#d7e0db] p-3 pr-12 text-sm leading-6 outline-none focus:border-forest"/><button className="absolute right-3 top-3 text-[#7a867f]" aria-label={`复制${label}`}><Copy size={16}/></button></div></div>}
