"use client";
import Link from "next/link";
import { AlertTriangle, ArrowRight, Check, ChevronRight, Database, Filter, Play, ShieldCheck, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { opportunities } from "@/lib/mock-data";

type Candidate=(typeof opportunities)[number]&{variants:number;listed:string;seller:string;packageSize:string;supplyDemand:number;aba:number;trend:string;intent:"S"|"A"|"B"|"C";stockRisk:string;differentiation:string;completeness:string;recommendation:"A"|"B"|"C";risk:string};
const candidates:Candidate[]=opportunities.map((item,index)=>({...item,variants:[2,1,3,2,3,1][index],listed:["8个月","6个月","9个月","11个月","7个月","5个月"][index],seller:index===2?"中国香港":"中国大陆",packageSize:index===3?"Large Standard":"Small Standard",supplyDemand:[14.8,12.6,16.2,11.4,13.1,10.8][index],aba:[21,26,18,29,24,28][index],trend:["稳定上涨","季节性上涨","稳定","稳定上涨","稳定","小幅上涨"][index],intent:(["S","S","A","A","A","B"] as const)[index],stockRisk:["低","中","低","低","中","低"][index],differentiation:["高","中","高","中","中","高"][index],completeness:index<3?"完整":"部分数据待复核",recommendation:(["A","A","A","B","B","C"] as const)[index],risk:["磁力与背胶稳定性需打样","旺季结束后需控制库存","内衬和拉链品质一致性","大号包装可能抬高 FBA 费","同质化较高","核心词 CPC 偏高"][index]}));
const stages=[["批量产品初筛","1–2 次调用","获取 20–50 个候选"],["本地硬条件过滤","0 次调用","最多保留 15 个"],["批量市场验证","1–2 次调用","最多保留 10 个"],["核心词与趋势验证","1–2 次调用","输出 Top 3 后停止"]];

export function OpportunityCenter(){
 const [started,setStarted]=useState(false);const [price,setPrice]=useState(20);const [reviews,setReviews]=useState(350);const [rating,setRating]=useState(4.3);const [salesMin,setSalesMin]=useState(50);const [salesMax,setSalesMax]=useState(2000);const [keyword,setKeyword]=useState("");const [season,setSeason]=useState("不限制");
 const rows=useMemo(()=>candidates.filter(i=>i.price>=price&&i.reviewCount<=reviews&&i.rating>=rating&&i.estimatedMonthlySales>=salesMin&&i.estimatedMonthlySales<=salesMax&&(!keyword||`${i.productName} ${i.keyword}`.toLowerCase().includes(keyword.toLowerCase()))),[price,reviews,rating,salesMin,salesMax,keyword]);
 const topThree=rows.slice().sort((a,b)=>b.opportunityScore-a.opportunityScore).slice(0,3);
 return <div className="space-y-5">
  <section className="overflow-hidden rounded-2xl border border-[#dce5e0] bg-white shadow-panel"><div className="flex flex-col gap-4 border-b border-[#e4eae7] bg-[#f9fcfa] p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 font-bold"><Filter size={18} className="text-forest"/>精铺选品参数</div><p className="mt-1 text-sm text-[#6f7b74]">A 类硬筛选优先批量获取，B 类指标仅验证最终候选。</p></div><div className="flex items-center gap-3 rounded-xl border border-[#cee1d7] bg-white px-4 py-2.5"><Database size={17} className="text-forest"/><div><p className="text-xs text-[#748078]">SellerSprite 调用预算</p><p className="text-sm font-bold"><span className="text-forest">0</span> / 8 次硬上限</p></div></div></div>
   <div className="grid gap-x-5 gap-y-4 p-5 md:grid-cols-2 xl:grid-cols-4"><Field label="目标销售时间"><input defaultValue="2027年1月–3月" className="field"/></Field><Field label="参考数据周期"><input defaultValue="重点参考2026年1月–3月" className="field"/></Field><Field label="类目要求"><input defaultValue="不做服装、鞋靴、珠宝" className="field"/></Field><Field label="季节属性"><select value={season} onChange={e=>setSeason(e.target.value)} className="field"><option>不限制</option><option>全年品</option><option>情人节</option><option>母亲节</option><option>圣诞节</option></select></Field><NumberField label="最低售价（美元）" value={price} set={setPrice}/><NumberField label="最高 Review 数" value={reviews} set={setReviews}/><NumberField label="最低评分" value={rating} set={setRating} step={0.1}/><Field label="变体数"><select className="field"><option>1–3</option><option>1</option><option>1–5</option><option>不限制</option></select></Field><NumberField label="最低月销量" value={salesMin} set={setSalesMin}/><NumberField label="最高月销量" value={salesMax} set={setSalesMax}/><Field label="包含关键词"><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="不限制或输入关键词" className="field"/></Field><Field label="包装尺寸"><select className="field"><option>标准尺寸</option><option>Small Standard</option><option>Large Standard</option><option>不限制</option></select></Field></div>
   <div className="flex flex-col gap-3 border-t border-[#e4eae7] bg-[#fbfdfc] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-[#66736b]">辅助门槛：供需比 &gt;10 · ABA 集中度 &lt;30% · 精准 PPC &lt;$0.70 · 优先自然流量 &gt;70%</p><button onClick={()=>setStarted(true)} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-forest px-5 text-sm font-semibold text-white"><Play size={16}/>开始批量筛选</button></div></section>
  <section className="rounded-2xl border border-[#dce5e0] bg-white p-5 shadow-panel"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">额度受控的筛选漏斗</h2><p className="mt-1 text-sm text-[#748078]">先批量、再本地过滤；绝不逐个 ASIN 循环查询。</p></div>{started&&<span className="flex items-center gap-1.5 rounded-full bg-[#e9f6ef] px-3 py-1.5 text-xs font-bold text-forest"><Check size={14}/>模拟筛选完成</span>}</div><div className="grid gap-3 lg:grid-cols-4">{stages.map((s,i)=><div key={s[0]} className="relative rounded-xl border border-[#dce5e0] p-4"><span className="grid h-7 w-7 place-items-center rounded-lg bg-forest text-xs font-bold text-white">{i+1}</span><p className="mt-3 font-semibold">{s[0]}</p><p className="mt-1 text-xs font-medium text-forest">{s[1]}</p><p className="mt-1 text-xs text-[#7a867f]">{s[2]}</p>{i<3&&<ArrowRight className="absolute -right-5 top-1/2 z-10 hidden text-[#aebbb4] lg:block" size={18}/>}</div>)}</div></section>
  <section className="overflow-hidden rounded-2xl border border-[#dce5e0] bg-white shadow-panel"><div className="flex items-center justify-between p-5"><div><h2 className="font-bold">最终候选清单</h2><p className="mt-1 text-sm text-[#748078]">当前条件筛出 {rows.length} 个；缺失字段标记待复核，不为填表追加调用。</p></div><span className="rounded-full bg-[#f0f3f1] px-3 py-1.5 text-xs font-semibold">模拟数据</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1700px] text-left text-sm"><thead className="bg-[#f7faf8] text-xs text-[#748078]"><tr>{["排名","产品名称 / ASIN","售价","月销量","Review / 评分","变体","上架时间","卖家所在地","包装尺寸","核心关键词","搜索量","供需比","ABA集中度","精准PPC","趋势","意图","库存风险","差异化","机会分","推荐","主要风险","数据完整度"].map(h=><th key={h} className="whitespace-nowrap px-3 py-3.5 first:pl-5">{h}</th>)}</tr></thead><tbody>{rows.map((i,n)=><tr key={i.id} className="border-t border-[#edf1ef]"><td className="pl-5 font-bold">{n+1}</td><td className="px-3 py-4"><Link href={`/opportunities/${i.id}`} className="font-semibold hover:text-forest">{i.productName}</Link><p className="mt-1 font-mono text-xs text-[#7a867f]">{i.asin}</p></td><td>${i.price}</td><td>{i.estimatedMonthlySales.toLocaleString()}</td><td>{i.reviewCount} / {i.rating}★</td><td>{i.variants}</td><td>{i.listed}</td><td>{i.seller}</td><td>{i.packageSize}</td><td className="max-w-[190px] truncate">{i.keyword}</td><td>{i.searchVolume.toLocaleString()}</td><td>{i.supplyDemand}</td><td>{i.aba}%</td><td>${i.estimatedCpc}</td><td>{i.trend}</td><td><IntentBadge value={i.intent}/></td><td>{i.stockRisk}</td><td>{i.differentiation}</td><td className="font-bold text-forest">{i.opportunityScore}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${i.recommendation==="A"?"bg-forest text-white":i.recommendation==="B"?"bg-[#fff3d9] text-[#916000]":"bg-[#f1f3f2] text-[#67736c]"}`}>{i.recommendation}级</span></td><td className="max-w-[220px] px-3 text-[#66736b]">{i.risk}</td><td className="pr-5"><span className={i.completeness==="完整"?"text-forest":"text-amber-700"}>{i.completeness}</span></td></tr>)}</tbody></table></div>{rows.length===0&&<div className="p-12 text-center text-sm text-[#748078]">当前硬性条件下没有候选，请调整参数；系统不会为了凑数自动放宽门槛。</div>}</section>
  {topThree.length>0&&<section><div className="mb-4 flex items-center gap-2"><Sparkles size={18} className="text-forest"/><h2 className="font-bold">最终 Top 3</h2></div><div className="grid gap-4 xl:grid-cols-3">{topThree.map((i,n)=><article key={i.id} className="rounded-2xl border border-[#dce5e0] bg-white p-5 shadow-panel"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-forest">TOP {n+1}</p><h3 className="mt-1 text-lg font-bold">{i.productName}</h3></div><span className="text-3xl font-bold text-forest">{i.opportunityScore}</span></div><dl className="mt-5 space-y-3 text-sm"><Decision label="为什么值得做" value={`搜索意图 ${i.intent} 级，Review 门槛可进入，售价与需求结构匹配精铺测试。`}/><Decision label="最大优势" value={`${i.differentiation}差异化空间，供需比 ${i.supplyDemand}，ABA 集中度 ${i.aba}%。`}/><Decision label="最大风险" value={i.risk}/><Decision label="下一步验证" value="获取真实采购价、包装数据并完成小批量样品测试。"/></dl><Link href={`/opportunities/${i.id}`} className="mt-5 flex items-center justify-end gap-1 text-sm font-semibold text-forest">查看完整证据<ChevronRight size={16}/></Link></article>)}</div><div className="mt-4 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><p>选品结果到此停止，不自动进入供应商调研或广告关键词验证。只有你明确选定产品后，才为该产品筛选 5–10 个精准广告词。</p></div></section>}
  <section className="flex items-center gap-3 rounded-2xl border border-[#cfe3d8] bg-[#f0f8f4] p-5"><ShieldCheck size={24} className="shrink-0 text-forest"/><div><p className="font-semibold text-forest">本次模拟 SellerSprite 调用：0 次</p><p className="mt-1 text-sm text-[#5e7468]">筛选、排序、评分、意图判断和风险判断全部在本地完成；真实接口接入后仍执行最多 8 次的硬停止规则。</p></div></section>
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}{children}</label>}
function NumberField({label,value,set,step=1}:{label:string;value:number;set:(n:number)=>void;step?:number}){return <Field label={label}><input type="number" value={value} step={step} onChange={e=>set(Number(e.target.value))} className="field"/></Field>}
function IntentBadge({value}:{value:Candidate["intent"]}){const style={S:"bg-forest text-white",A:"bg-[#e7f6ed] text-forest",B:"bg-[#fff3d9] text-[#916000]",C:"bg-red-50 text-red-700"}[value];return <span className={`rounded-md px-2 py-1 text-xs font-bold ${style}`}>{value}级</span>}
function Decision({label,value}:{label:string;value:string}){return <div><dt className="font-semibold text-[#46534c]">{label}</dt><dd className="mt-1 leading-5 text-[#748078]">{value}</dd></div>}
