import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Star } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { opportunityRepository } from "@/lib/repositories/opportunities";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const product = await opportunityRepository.findById(id); if (!product) notFound();
  const scores = [["需求分", product.demandScore], ["竞争分", product.competitionScore], ["利润分", product.profitScore], ["季节性分", product.seasonalityScore]] as const;
  const statusLabel = { Watching: "观察中", Validating: "验证中", Shortlisted: "已入围", Rejected: "已淘汰" }[product.status];
  return <AppShell><div className="mx-auto max-w-[1400px] px-4 py-8 sm:px-7 lg:px-10"><Link href="/opportunities" className="inline-flex items-center gap-2 text-sm font-semibold text-forest"><ArrowLeft size={16}/>返回选品中心</Link><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-forest">{product.category}</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{product.productName}</h1><p className="mt-2 text-sm text-[#6f7b74]">核心关键词：{product.keyword} · ASIN：{product.asin}</p></div><span className="w-fit rounded-full bg-forest px-3 py-1.5 text-sm font-semibold text-white">{statusLabel}</span></div><div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-[#dce5e0] bg-white p-6 shadow-panel md:col-span-2"><h2 className="font-bold">综合机会分</h2><div className="mt-5 flex items-center gap-5"><span className="text-6xl font-bold tracking-tight text-forest">{product.opportunityScore}</span><div className="grid flex-1 gap-3">{scores.map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between text-sm"><span>{label}</span><b>{value}</b></div><div className="h-2 rounded-full bg-[#e8eeeb]"><div className="h-full rounded-full bg-forest" style={{width:`${value}%`}}/></div></div>)}</div></div></div><div className="rounded-2xl border border-[#dce5e0] bg-white p-6 shadow-panel"><h2 className="font-bold">市场快照</h2><dl className="mt-5 space-y-4 text-sm">{[["售价", `$${product.price}`], ["预估月营收", `$${product.estimatedMonthlyRevenue.toLocaleString()}`], ["预估月销量", product.estimatedMonthlySales.toLocaleString()], ["评论数", product.reviewCount.toLocaleString()], ["评分", `${product.rating} ★`], ["BSR 排名", `#${product.bsr.toLocaleString()}`]].map(([k,v])=><div key={k} className="flex justify-between border-b border-[#edf1ef] pb-3 last:border-0"><dt className="text-[#748078]">{k}</dt><dd className="font-semibold">{v}</dd></div>)}</dl></div></div></div></AppShell>;
}
